baseURL = "https://anieqsaidi.web.app"
languageCode = "en-us"
title = "Talent Has No Face."
theme = "kross-hugo-portfolio-template"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Archives"
  URL = "archives"
  weight = 3

[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is a résumé portal created by Anieq Saidi."
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "G-3WQ9N4F99N"

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = true
  formAction = "#" #contact form works with formspree.io

  [params.footer]
  email = "aniq_mpp@ump.edu.my"
  phone = "+60 19-242 7685"
  address = "Kuala Lumpur, Malaysia"